SELECT * FROM Usuario;
SELECT * FROM Reserva;
SELECT * FROM Pagamento;
SELECT * FROM Quarto;
SELECT * FROM Vaga;
SELECT * FROM Peculiaridades;
SELECT * FROM Reserva_Vaga;
SELECT * FROM Quarto_Peculiaridades;
SELECT * FROM Vaga_Peculiaridades;